In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
plt.rc('font', family='Malgun Gothic')
plt.rc('axes', unicode_minus=False)

In [13]:
df = pd.read_csv('data/Exam_Score_Prediction.csv')
df

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19997,18,other,bba,6.50,71.3,yes,5.0,good,self-study,low,easy,86.5
19996,19998,18,male,b.com,3.71,41.6,no,5.9,average,coaching,medium,moderate,60.9
19997,19999,19,other,diploma,7.88,68.2,yes,4.6,poor,group study,low,easy,64.5
19998,20000,19,male,bba,4.60,76.3,no,6.1,good,self-study,medium,moderate,79.0
19999,20001,20,male,b.sc,7.50,47.9,yes,7.5,poor,coaching,medium,moderate,71.0

In [14]:
df.isna().sum()

student_id          0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
exam_score          0
dtype: int64

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        20000 non-null  int64
 1   age               20000 non-null  int64
 2   gender            20000 non-null  str
 3   course            20000 non-null  str
 4   study_hours       20000 non-null  float64
 5   class_attendance  20000 non-null  float64
 6   internet_access   20000 non-null  str
 7   sleep_hours       20000 non-null  float64
 8   sleep_quality     20000 non-null  str
 9   study_method      20000 non-null  str
 10  facility_rating   20000 non-null  str
 11  exam_difficulty   20000 non-null  str
 12  exam_score        20000 non-null  float64
dtypes: float64(4), int64(2), str(7)
memory usage: 2.0 MB

In [16]:
df.describe()

,student_id,age,study_hours,class_attendance,sleep_hours,exam_score
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000
mean,10000.504600,20.473300,4.007604,70.017365,7.00856,62.513225
std,5773.654959,2.284458,2.308313,17.282262,1.73209,18.908491
min,1.000000,17.000000,0.080000,40.600000,4.10000,19.599000
25%,5000.750000,18.000000,2.000000,55.100000,5.50000,48.800000
50%,10000.500000,20.000000,4.040000,69.900000,7.00000,62.600000
75%,15000.250000,22.000000,6.000000,85.000000,8.50000,76.300000
max,20001.000000,24.000000,7.910000,99.400000,9.90000,100.000000

In [18]:
df.describe(include=['str'])

,gender,course,internet_access,sleep_quality,study_method,facility_rating,exam_difficulty
count,20000,20000,20000,20000,20000,20000,20000
unique,3,7,2,3,5,3,3
top,other,bca,yes,average,self-study,medium,moderate
freq,6726,2902,16988,6694,4079,6760,9878

In [ ]:
df.value_counts(df[''])

student_id  age  gender  course   study_hours  class_attendance  internet_access  sleep_hours  sleep_quality  study_method   facility_rating  exam_difficulty  exam_score
1           17   male    diploma  2.78         92.9              yes              7.4          poor           coaching       low              hard             58.9          1
2           23   other   bca      3.37         64.8              yes              4.6          average        online videos  medium           moderate         54.8          1
3           22   male    b.sc     7.88         76.8              yes              8.5          poor           coaching       high             moderate         90.3          1
4           20   other   diploma  0.67         48.4              yes              5.8          average        online videos  low              moderate         29.7          1
5           20   female  diploma  0.89         71.6              yes              9.8          poor           coaching       low              moderate         43.7          1
                                                                                                                                                                            ..
19997       18   other   bba      6.50         71.3              yes              5.0          good           self-study     low              easy             86.5          1
19998       18   male    b.com    3.71         41.6              no               5.9          average        coaching       medium           moderate         60.9          1
19999       19   other   diploma  7.88         68.2              yes              4.6          poor           group study    low              easy             64.5          1
20000       19   male    bba      4.60         76.3              no               6.1          good           self-study     medium           moderate         79.0          1
20001       20   male    b.sc     7.50         47.9              yes              7.5          poor           coaching       medium           moderate         71.0          1
Name: count, Length: 20000, dtype: int64